services:
  postgres:
    image: postgres:${TAG_IMAGE_DB}
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - kub_post_vol:/var/lib/postgresql/data
    networks:
      - kub_net

  web-site:
    image: vinny6202/kube_news:${TAG_IMAGE_APP}
    depends_on:
      - postgres
    container_name: web-site
    build: 
      context: ./src
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_USERNAME=${POSTGRES_USER}
      - DB_DATABASE=${POSTGRES_DB}
      - DB_HOST=postgres
    networks:
      - kub_net



volumes:
  kub_post_vol:
    name: kub_post_vol

networks:
  kub_net:
    name: kub_net
    driver: bridge

